version: '3'
services:
  php:
    image: movecloser/php:8.1-full
    environment:
      DB_CONNECTION: "sqlite"
      SETTINGS_CONNECTION: "sqlite"
      DB_NAME: ":memory:"
    volumes:
      - .:/var/www:rw,cached
