name: Test

on:
  pull_request:
    types: [opened, reopened]

jobs:
  run-phpunit:
    name: Run PhpUnit tests
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        composer install --ignore-platform-reqs -v

    - name: Run Testsuite
      run: |
        vendor/bin/phpunit --testdox --log-junit unit-report.xml

#    - name: Prepare Container
#      run: |
#        docker pull movecloser/php:8.0-full
#        CMD="composer install --ignore-platform-reqs -v"
#        docker run --rm -i -e BUILD=1 -e HOME=/var/www/ -v "$PWD:/var/www/" movecloser/php:8.0-full sh -c "$CMD"
#    - name: Run Tests
#      run: |
#        CMD="php vendor/bin/phpunit --testdox --log-junit unit-report.xml"
#        docker run --rm -i -e BUILD=1 -e HOME=/var/www/ -v "$PWD:/var/www/" movecloser/php:8.0-full sh -c "$CMD"
